updated yaml build file

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -14,6 +14,8 @@ workflows:
     environment:
       groups:
         - pure-notes
+      android_signing:
+        - CodedByKay.PureNotes.CodeMagic.Keystore
     scripts:
       - name: Determine Environment
         script: |
@@ -43,13 +45,30 @@ workflows:
       - name: Sign APK (Release Only)
         script: |
           if [ "$BUILD_TYPE" = "release" ]; then
-            echo "Signing release APK..."
-            # Replace with your actual signing commands
-            jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $KEYSTORE_PATH -storepass $KEYSTORE_PASSWORD app/build/outputs/apk/release/app-release-unsigned.apk $KEY_ALIAS
-            # Optionally, align the APK
-            zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk
+          echo "Signing release APK..."
+          # Define paths
+          UNSIGNED_APK="app/build/outputs/apk/release/app-release-unsigned.apk"
+          SIGNED_APK="app/build/outputs/apk/release/app-release.apk"
+          
+          # Verify the APK exists
+          if [ ! -f "$UNSIGNED_APK" ]; then
+          echo "Unsigned APK not found at $UNSIGNED_APK"
+          exit 1
+          fi
+          
+          # Sign the APK using jarsigner
+          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore "$CM_KEYSTORE_PATH" -storepass "CM_$KEYSTORE_PASSWORD" "$UNSIGNED_APK" "$CM_KEY_ALIAS"
+          
+          # Verify the APK is signed
+          jarsigner -verify -verbose -certs "$UNSIGNED_APK"
+          
+          # Align the APK using zipalign
+          echo "Aligning the APK..."
+          zipalign -v -p 4 "$UNSIGNED_APK" "$SIGNED_APK"
+          
+          echo "Signed and aligned APK is available at $SIGNED_APK"
           else
-           echo "Skipping signing since this is a debug build"
+          echo "Skipping signing since this is a debug build"
           fi
 
       - name: Conditionally Start Emulator
@@ -61,7 +80,7 @@ workflows:
             adb shell input keyevent 82
             echo "Emulator is ready."
           else
-          
+            echo "Skipping emulator startup as this is not a Linux environment."
           fi
 
       - name: Conditionally Run Instrumentation Tests
